### ISSUE TITLE
Schema diagram image is not loaded

### ISSUE THREAD

**Issue by mushtaqrizvihw** [julianhyde/foodmart-data-hsqldb#1]
Schema diagram image at https://github.com/julianhyde/foodmart-data-hsqldb/blob/master/README.md is not loaded properly. Please have a look, screenshot is attached.
![image_notloaded](https://cloud.githubusercontent.com/assets/19439248/16933771/6d86e47e-4d05-11e6-91ad-1cd04c9a97f0.png)

**Comment by julianhyde** [comment]
Fixed in 2172ba879ffe6ba4fa40c9bcacc6bbf424978f4f.
